/**
 * Auto-generated by scripts/inject-public-env.js - do not edit by hand.
 * Empty strings keep analytics/verification disabled safely.
 */
export const publicEnv = Object.freeze({
  GA_MEASUREMENT_ID: "",
  CLARITY_PROJECT_ID: "",
  GOOGLE_SITE_VERIFICATION: "",
});
